"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var cors_1 = require("cors");
var applicationRoutes_1 = require("./routes/applicationRoutes");
var app = (0, express_1.default)();
app.use((0, cors_1.default)());
app.use(express_1.default.json());
app.use('/api/applications', applicationRoutes_1.default);
exports.default = app;
